version: "3"

services:
  joke_database:
    container_name: joke_database
    image: mysql:5.7
    restart: always
    volumes:
      - joke_db:/var/lib/mysql
    ports:
      - "4306:3306"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  joke_app:
    build:
      context: .
    container_name: joke_app
    restart: always
    environment:
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
       HOST: ${HOST}
       PORT: ${PORT}
    volumes:
      - .:/home/joke
    ports:
      - 8001:8001
    depends_on:
      - joke_database
  
  # nginx:
  #   build: ./nginx
  #   ports:
  #     - 1337:80
  #   depends_on:
  #     - obadge_app
  #   volumes:
  #     - static_volume:/home/staticfiles
  #     - media_volume:/home/mediafiles
volumes:
  joke_db:
  # static_volume:
  # media_volume: